[package]
name = "beaverstudio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "beaverstudio"
crate-type = ["cdylib"]

[dependencies]
image = "0.25.5"
pyo3 = "0.23.3"
